name = "galactic-parallax-api"
main = "src/index.ts"
compatibility_date = "2025-05-29"
workers_dev = false

[vars]
AUTH0_DOMAIN = "neontowel-dev.eu.auth0.com"
AUTH0_AUDIENCE = "galactic-parallax.apis.neontowel.dev"
