name = "galactic-parallax-api"
main = "src/index.ts"
compatibility_date = "2025-05-25"
workers_dev = false

routes = [{ pattern = "parallax.apis.neontowel.dev", custom_domain = true }]

[vars]
AUTH0_DOMAIN = "neontowel-dev.eu.auth0.com"
AUTH0_AUDIENCE = "https://parallax.apis.neontowel.dev"

# Google Custom Search API Configuration
# These should be set as secrets in production:
# wrangler secret put GOOGLE_SEARCH_API_KEY
# wrangler secret put GOOGLE_SEARCH_ENGINE_ID
# GOOGLE_SEARCH_API_KEY = "your-api-key-here"
# GOOGLE_SEARCH_ENGINE_ID = "your-search-engine-id-here"

# Serper API Configuration
# These should be set as secrets in production:
# wrangler secret put SERPER_API_KEY
# SERPER_API_KEY = "your-api-key-here"

# Zenserp API Configuration
# These should be set as secrets in production:
# wrangler secret put ZENSERP_API_KEY
# ZENSERP_API_KEY = "your-api-key-here"

[[d1_databases]]
binding = "DB"
database_name = "parallax"
database_id = "bf1447cb-ee86-4f45-8438-8093ba271002"
