name = "galactic-parallax-api"
main = "src/index.ts"
compatibility_date = "2025-05-29"
workers_dev = false

routes = [
  { pattern = "parallax.apis.neontowel.dev/*", custom_domain = true }
]

[vars]
AUTH0_DOMAIN = "neontowel-dev.eu.auth0.com"
AUTH0_AUDIENCE = "parallax.apis.neontowel.dev"
